### PR TITLE
Initial support for Python 3

### PR DESCRIPTION
**Pull request by mcg1969**
I've been running Airflow successfully on Python 3 for awhile, so it seems reasonable to see if we can get this recipe working for it.

### CODE REVIEW

**Comment by sodre** [comment]
I know the PR is working right now, do you want to change anything in it before I merge?

**Comment by mcg1969** [comment]
My only concern is that the CI builds only tested 27, as far as I can tell. I think the scripts need to be re-rendered. Seems a shame that it needs to be merged first before we can test that.

**Comment by mcg1969** [comment]
Ah, and I guess I need to increment the build number....

**Comment by sodre** [comment]
I think you can re-render on your side as well.

**Comment by mcg1969** [comment]
OK, I've re-rendered. Let's see how it goes...

**Comment by sodre** [comment]
I initiated a PR against flask-cache to get it to 3.6. Would you like to try the build for 3.5 so we can get it merged today, or do you rather wait for @conda-forge/flask-cache to merge their PR first?

**Comment by mcg1969** [comment]
Ah, sorry, I should have read your comment first. I think we can go either way with this. I'm not in a huge hurry; on the other hand, I run Python 3.5.

**Pull request merged**
