### PR TITLE
Py 310

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin  please rerender

**Comment by xylar** [comment]
Hi @marcelotrevisani, thanks for trying this out.  The approach for migrating to python 3.10 is a little different from what you're trying to do.

I would be willing to try migrating, though.  But I'm a little concerned because it seems that the latest release doesn't officially support python 3.10 yet:
https://github.com/apache/airflow/blob/2.2.4/setup.cfg#L56-L59

Do you have reason to think it will work anyway?

**Comment by xylar** [comment]
@marcelotrevisani, the process for migrating to python 3.10 (and in general for updating the versions of pinned packages maintained in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml) is to copy the migrator file into `.ci_support/migrations` as I have done in #82.  It's a process that should be taken care of either by a relatively expert conda-forge maintainer or by the bot that handles migration.  You can monitor package migration here:
https://conda-forge.org/status/

**Comment by marcelotrevisani** [comment]
I was testing the image first to see if it was going to pass

**Comment by xylar** [comment]
@marcelotrevisani, I see.  The rerender just undoes the changes you made, unfortunately.

I see from your website that you're a conda-forge core member so sorry for talking to you as if you don't know what you're doing.  No offense meant, I just know some folks come to conda-forge without much knowledge of how things work.

**Comment by marcelotrevisani** [comment]
just checking if the smithy needed to do any other modification
because the image failed before

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani, I see. The rerender just undoes the changes you made, unfortunately.
> 
> I see from your website that you're a conda-forge core member so sorry for talking to you as if you don't know what you're doing. No offense meant, I just know some folks come to conda-forge without much knowledge of how things work.

no worries mate :)

**Comment by marcelotrevisani** [comment]
I am closing this, I was just doing some test if python 3.10 could be added here, but maybe we will need a new release from airflow, thanks :)

**Comment by xylar** [comment]
Okay, let me know if there's anything I can do to help.  I'll see what happens with #82.  It would at least be interesting to know if there are dependencies that aren't migrated and maybe need attention.

**Comment by marcelotrevisani** [comment]
adding this for reference
https://github.com/apache/airflow/pull/22050

**Pull request closed without merging**
