### PR TITLE
dev URL update

### PR DESCRIPTION
**Pull request by scopatz**
no need for a build number bump, since it is just some metadata

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@scopatz it looks like it will take more than just a dev update to make this work again.

**Comment by scopatz** [comment]
It doesn't need to pass to be merged, because a new package won't be uploaded

**Comment by sodre** [comment]
Closed by https://github.com/conda-forge/airflow-feedstock/commit/2cf8845d8854c766ff9b20aed14b538f31c7864a

**Pull request closed without merging**
