### PR TITLE
Manual architecture migration

### LINKED ISSUE #101: Not sure how to assist progress of migration for osx-arm64 while status is awaiting-parents (0)
### Comment:

I am not sure what the progress is of the migration, or if there is any dependency specific to airflow that is preventing it from appearing at [https://anaconda.org/conda-forge/airflow](https://anaconda.org/conda-forge/airflow). Thank you.

This PR was merged 2 days ago.
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4011/files

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #101

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The aarch64 (and maybe ppc64le) failures are likely because of tests that can't be run when cross-compilinig.

The osx-arm64 failure is:
```
/Users/runner/miniforge3/conda-bld/airflow-split_1675310198691/_build_env/etc/conda/activate.d/activate_clang_osx-arm64.sh: line 109: /Users/runner/miniforge3/conda-bld/airflow-split_1675310198691/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/env: Bad CPU type in executable
```
I don't understand that one at all.  It would seem like a bad `bin/env` is getting installed but it seems like the problem arises before even running `install_airflow.sh.`

Changing the shebang in `install_airflow.sh` from `#!/usr/bin/env bash` to `#!/bin/bash` didn't make a difference (no surprise).

I'll need to debug more at a later time.  Suggestions welcome!

**Comment by nickpowersys** [comment]
I am not knowledgable at all in cross-compiling. All I notice is the failure says "Bad CPU in executable". Could this have something to do with 32-bit versus 64-bit?

For example, https://www.technewstoday.com/bad-cpu-type-in-executable/

**Comment by xylar** [comment]
@nickpowersys, the error is not to do with 32-bit vs. 64-bit (though that was a good guess).  It is because we are compiling on osx-64 but I believe `bin/env` is being run that is osx-arm64. I'm just not sure how to fix it.

**Pull request closed without merging**
