### PR TITLE
1.10.2 update dependencies

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #24

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The required version of `pendulum` has not been built for python 3.7 (https://github.com/conda-forge/pendulum-feedstock/pull/17).  This seems to be the last missing requirement.

**Comment by xylar** [comment]
Next requirement not available for python 3.7 is the old version of `alembic` < 0.9.

**Comment by xylar** [comment]
Further incompatibilities with python 3.7:
* lxml >=3.6.0,<4.0
* tenacity==4.8.0
* flask-swagger==0.2.13
* tabulate>=0.7.5,<0.8.0

What a pain in the a**

**Comment by xylar** [comment]
It might be worth releasing this version without python 3.7 support.  What do you think, @sodre?

**Comment by xylar** [comment]
Update: tenacity 4.8.0 doesn't even support python 3.7, so I don't think there's any way to make airflow 1.10.2 build with python 3.7 (unless we ignore the constraints on package versions).

**Comment by xylar** [comment]
@conda-forge/airflow (@sodre), this is ready to review.

**Comment by sodre** [comment]
Thanks a lot @xylar !

**Comment by xylar** [comment]
Thanks, @sodre!

**Pull request merged**
